language: node_js
node_js:
  - '12'
install:
  - npm install
script:
  - npm run lint
  - npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: '47078866+anbhrm@users.noreply.github.com'
  api_key: $NPM_TOKEN
  on:
    tags: true
